version: "3.9"

services:
  database:
    image: postgres
    container_name: todo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=189035
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
